# Generated by Django 4.2.20 on 2026-03-04 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0014_player_card_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kickoff_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("lineup_pending", "Lineup pending"),
                            ("published", "Published"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "result_home",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "result_away",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "share_slug",
                    models.SlugField(blank=True, max_length=180, unique=True),
                ),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("lineup_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("import_payload", models.JSONField(blank=True, null=True)),
                ("lineup_payload", models.JSONField(blank=True, null=True)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                ("home_rating_avg", models.FloatField(default=0)),
                ("away_rating_avg", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_fixtures",
                        to="clubs.club",
                    ),
                ),
                (
                    "home_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_fixtures",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "ordering": ["kickoff_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="FixturePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")], max_length=8
                    ),
                ),
                (
                    "selection_status",
                    models.CharField(
                        choices=[
                            ("predicted", "Predicted"),
                            ("starting_xi", "Starting XI"),
                            ("bench", "Bench"),
                            ("played", "Played"),
                            ("unused", "Unused"),
                            ("hidden", "Hidden"),
                        ],
                        db_index=True,
                        default="predicted",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("auto_full_squad", "Auto full squad"),
                            ("manual", "Manual"),
                            ("paste_import", "Paste import"),
                            ("llm_match", "LLM match"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_confidence", models.CharField(blank=True, max_length=16)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "shirt_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "minutes_played",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_visible_public", models.BooleanField(default=True)),
                ("raw_name", models.CharField(blank=True, max_length=120)),
                ("position_label", models.CharField(blank=True, max_length=16)),
                ("is_captain", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixture_players",
                        to="clubs.club",
                    ),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixture_players",
                        to="matches.fixture",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixture_players",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["side", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-name"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="matches.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season__name", "number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=120)),
                (
                    "normalized_alias",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_aliases",
                        to="clubs.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_aliases",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="FixtureRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="matches.fixture",
                    ),
                ),
                (
                    "fixture_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="matches.fixtureplayer",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixture_ratings",
                        to="players.player",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixture_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fixture",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixtures",
                to="matches.round",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixtures",
                to="matches.season",
            ),
        ),
        migrations.CreateModel(
            name="ClubAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=120)),
                (
                    "normalized_alias",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_aliases",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("season", "number"), name="unique_round_per_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="playeralias",
            constraint=models.UniqueConstraint(
                fields=("player", "club", "normalized_alias"),
                name="unique_player_alias",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerating",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    models.Q(("session_key", ""), _negated=True),
                    _connector="OR",
                ),
                name="fixture_rating_user_or_session_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerating",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("fixture_player", "user"),
                name="unique_fixture_rating_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerating",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key", ""), _negated=True),
                fields=("fixture_player", "session_key"),
                name="unique_fixture_rating_per_session",
            ),
        ),
        migrations.AddIndex(
            model_name="fixtureplayer",
            index=models.Index(
                fields=["fixture", "side", "selection_status"],
                name="fixture_side_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixtureplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("player__isnull", False)),
                fields=("fixture", "player"),
                name="unique_fixture_player_assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(
                fields=["season", "kickoff_at"], name="fixture_season_kickoff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(
                fields=["status", "kickoff_at"], name="fixture_status_kickoff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixture",
            constraint=models.UniqueConstraint(
                fields=("home_club", "away_club", "kickoff_at"),
                name="unique_fixture_home_away_kickoff",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubalias",
            constraint=models.UniqueConstraint(
                fields=("club", "normalized_alias"), name="unique_club_alias"
            ),
        ),
    ]
