# Generated by Django 4.2.20 on 2025-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["player", "-created_at"], name="player_date_idx"
            ),
        ),
    ]
