# Generated by Django 4.2.20 on 2025-06-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_rating_player_date_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["user", "player"], name="user_player_idx"),
        ),
    ]
