# Generated by Django 4.2.20 on 2025-06-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
