# Generated by Django 4.2.20 on 2025-05-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="players/images/"),
        ),
        migrations.AddField(
            model_name="player",
            name="jersey_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="clubs.club",
            ),
        ),
    ]
