# Generated by Django 4.2.20 on 2025-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_delete_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
