# Generated by Django 4.2.20 on 2025-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_delete_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("GK", "Goalkeeper"),
                    ("DF", "Defender"),
                    ("MF", "Midfielder"),
                    ("FW", "Forward"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["club", "position"], name="club_position_idx"),
        ),
    ]
