# Generated by Django 4.2.20 on 2025-06-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0005_player_average_rating_player_total_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="clubs.club",
            ),
        ),
    ]
