# Generated by Django 4.2.20 on 2025-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_player_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
