# Generated by Django 4.2.20 on 2025-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_player_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
