# Generated by Django 4.2.20 on 2025-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0008_player_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="tweet_urls",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
