# Generated by Django 4.2.20 on 2026-01-25 18:55

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0009_player_tweet_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gif_urls",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=players.models.player_photo_upload_to
            ),
        ),
    ]
