# Generated by hand - add ai_response fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ai_response",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="ai_generated_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
