# Generated by Django 4.2.20 on 2026-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ai_response",
            field=models.TextField(
                blank=True, help_text="Humorous AI response to the comment", null=True
            ),
        ),
    ]
